version: '3'
services:
  telegram-message:
    container_name: telegram-message
    build:
      context: .
      dockerfile: Dockerfile
    image: telegram-message
    ports:
      - 8080:8080
#    depends_on:
#      - mysql
    environment:
      - GITLAB_TOKEN=${GITLAB_TOKEN}
    networks:
      - backend
    extra_hosts:
      - "host.docker.internal:host-gateway"

networks:
  backend:
    name: backend
    driver: bridge
    external: true